import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { z } from "zod";

export const exportAppealPacket = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => z.object({ appeal_id: z.string() }).parse(d))
  .handler(async ({ data, context }) => {
    const { supabase } = context;
    const { data: appeal, error } = await supabase
      .from("appeals")
      .select("*, authorization:authorizations(*, patient:patients(*))")
      .eq("id", data.appeal_id).single();
    if (error || !appeal) throw new Error("Appeal not found");

    const { PDFDocument, StandardFonts, rgb } = await import("pdf-lib");
    const doc = await PDFDocument.create();
    const font = await doc.embedFont(StandardFonts.Helvetica);
    const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

    const addPage = () => doc.addPage([612, 792]);
    let page = addPage();
    let y = 750;
    const left = 50;
    const right = 562;

    const drawText = (text: string, opts: { bold?: boolean; size?: number; color?: [number, number, number] } = {}) => {
      const size = opts.size ?? 11;
      const f = opts.bold ? fontBold : font;
      const color = opts.color ? rgb(...opts.color) : rgb(0.1, 0.1, 0.15);
      const maxWidth = right - left;
      const words = text.split(/\s+/);
      let line = "";
      const lines: string[] = [];
      words.forEach((w) => {
        const test = line ? `${line} ${w}` : w;
        if (f.widthOfTextAtSize(test, size) > maxWidth) {
          lines.push(line);
          line = w;
        } else line = test;
      });
      if (line) lines.push(line);
      lines.forEach((ln) => {
        if (y < 60) { page = addPage(); y = 750; }
        page.drawText(ln, { x: left, y, size, font: f, color });
        y -= size + 4;
      });
    };

    const section = (title: string) => {
      y -= 10;
      if (y < 100) { page = addPage(); y = 750; }
      drawText(title.toUpperCase(), { bold: true, size: 13, color: [0.06, 0.4, 0.5] });
      y -= 4;
      page.drawLine({ start: { x: left, y: y + 6 }, end: { x: right, y: y + 6 }, thickness: 0.5, color: rgb(0.8, 0.85, 0.88) });
      y -= 4;
    };

    // Header
    drawText("PRIORFLOW AI", { bold: true, size: 18, color: [0.06, 0.4, 0.5] });
    drawText("Appeal Packet", { size: 12, color: [0.4, 0.45, 0.5] });
    y -= 16;

    section("Patient");
    drawText(`${appeal.authorization.patient.first_name} ${appeal.authorization.patient.last_name}`, { bold: true });
    drawText(`MRN: ${appeal.authorization.patient.mrn}   DOB: ${appeal.authorization.patient.dob ?? "n/a"}`);
    drawText(`Insurance: ${appeal.authorization.patient.insurance_payer ?? "n/a"} — Member ${appeal.authorization.patient.insurance_member_id ?? "n/a"}`);

    section("Authorization");
    drawText(`Diagnosis: ${appeal.authorization.diagnosis ?? "n/a"} (${appeal.authorization.diagnosis_code ?? ""})`);
    drawText(`Procedure: ${appeal.authorization.procedure_requested ?? "n/a"} (${appeal.authorization.procedure_code ?? ""})`);
    drawText(`Payer: ${appeal.authorization.payer ?? "n/a"}   Status: ${appeal.authorization.status}`);
    drawText(`Appeal version: v${appeal.version}   Status: ${appeal.status}`);

    if (appeal.appeal_letter) { section("Appeal Letter"); drawText(appeal.appeal_letter); }
    if (appeal.clinical_justification) { section("Clinical Justification"); drawText(appeal.clinical_justification); }
    if (appeal.supporting_evidence) { section("Supporting Evidence"); drawText(appeal.supporting_evidence); }
    if (appeal.payer_response_draft) { section("Payer Response Draft"); drawText(appeal.payer_response_draft); }

    section("Generated");
    drawText(`This packet was generated by PriorFlow AI on ${new Date().toLocaleString()}.`, { size: 9, color: [0.5, 0.5, 0.55] });

    const bytes = await doc.save();
    // Convert to base64 for transport
    let binary = "";
    const chunk = 0x8000;
    for (let i = 0; i < bytes.length; i += chunk) {
      binary += String.fromCharCode(...Array.from(bytes.subarray(i, i + chunk)));
    }
    return { base64: btoa(binary), filename: `appeal-${appeal.authorization.patient.last_name}-v${appeal.version}.pdf` };
  });
